# This workflow will install Python dependencies and run tests with PyTest using Python 3.8
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set Python version
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Set up submodules and submodule dependencies
      - name: Set up submodule and submodule dependencies
        run: |
          git submodule update --init --recursive --remote
          pip install -r ./modules/common/requirements.txt

      # Install pathing dependencies
      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install zbar library to resolve pyzbar import error
      - name: Install zbar library
        run: sudo apt-get install libzbar0

      # Run tests with PyTest
      - name: Run tests
        run: pytest -vv
